language: elixir
matrix:
  include:
    - otp_release: 22.1
      elixir: 1.10
env:
  global:
    - MIX_HOME=$HOME/.mix
cache:
  directories:
  - $HOME/.mix
  - deps
  - _build
  - demos/my_system/deps
  - demos/my_system/_build
script:
  - MIX_ENV=test mix compile --force --warnings-as-errors
  - mix docs
  - mix test
  - mix format
  - MIX_ENV=test mix credo list
  - mix dialyzer
